[package]
name = "concurrent-list"
version = "0.0.1"

edition = "2021"
rust-version = "1.56"

description = "An append-only, single-writer multi-reader unrolled linked list"
repository = "https://github.com/espadolini/concurrent-list"
license = "MIT OR Apache-2.0"

[dependencies]
